### ISSUE TITLE
FInish the design/layout for production

### ISSUE THREAD

**Issue by jonathan-lindqvist** [MSaurus/new-tab-page#20]
If we want people to use our extension we need to make the design appealing, we will build upon the mock-up that @MSaurus created! We also need to clean up the stuff we are not using at the moment, example; the weather icon. 

The question is if we should use grid or flex? @MSaurus

**Comment by MSaurus** [comment]
Hmm, I think we should use both. It depends on how we need to make the layout. Grid is good if we need to place things in a 2d grid and flex is good to use when we just want to place things a horizontal or vertical line
